# Set environments
set-option -g default-shell "$SHELL"
set-environment -g PATH "$HOME/.cargo/bin:$PATH"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'AngryMorrocoy/tmux-neolazygit'

# Catppuccin
set -g @catppuccin_flavor 'macchiato' # latte, frappe, macchiato or mocha
set -g @catppuccin_window_status_style "basic"
set -g status-right-length 100
set -g status-left-length 100
set -g status-left "#{E:@catppuccin_status_session}"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g status-right ""
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"

# change prefix to C-a
unbind C-b
set-option -g prefix C-a

# Temux sessionizer
bind-key -n C-f display-popup -E tms

# Lazygit
set -g @open-lazygit 'G'

set -g default-terminal "tmux-256color"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
